### ISSUE TITLE
Idempotency and Lambda timeouts

### ISSUE THREAD

**Issue by n2N8Z** [awslabs/aws-lambda-powertools-python#1038]
**Is your feature request related to a problem? Please describe.**
Currently if a lambda timesout the idempotency item is left in the 'INPROGRESS' status and subsequent lambda retries fail with IdempotencyAlreadyInProgressError.

**Describe the solution you'd like**
Add an additional field to the persistence record e.g. function_timeout and store in it the timestamp when the lambda will timeout: now().timestamp() + int(context.get_remaining_time_in_millis() / 1000)
Expand the DDB condition: OR function_timeout < :now

**Describe alternatives you've considered**
Create a signal handler in the lambda that raises an exception just before the lambda is about to timeout.

**Additional context**
N/A

**Comment by heitorlessa** [comment]
@n2N8Z and everyone - We have recently found a better way to solve this using an internal no-op extension.

POC below - This allows us to receive a `SIGTERM` in a background thread to do any cleanup, like changing the status of the idempotency data record -- we let it takes its course if we don't receive a `SIGTERM` signal.

https://gist.github.com/heitorlessa/4aad06c39a1d520ff8c42adc72b0bcd5

**Comment by heitorlessa** [comment]
Yes, it is the Lambda scheduler who orchestrates sandboxes that are recycled when a time out happens. A SIGTERM is only sent if an internal or external extension is registered -- the former is what the POC above does using a no-op internal extension -- The lambda scheduler guarantees 500ms for this logic to run.

SIGALRM, in your experience, is 
not guaranteed as you discovered. For cleanup activities whether a timeout happens or not (clean exit,
Idle for X time), an external Lambda extension is more appropriate since you not only have 2s to handle it but it doesn't interfere in the request path (e.g., early return is possible while cleanup happens in the background).

https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html

Hopefully that explains it.

@cakepietoast had thoughts about both solutions not being good enough

**Comment by cakepietoast** [comment]
Fundamentally, I'm still of the mind that deleting INPROGRESS records violates idempotency. When this occurs and there are "stuck" INPROGRESS records, it is because there's no way for the utility to know whether the Lambda failed before, during, or after the unit of work its being asked to perform. As such, in the rare cases where this occurs, cases would need to be evaluated to understand the best approach. 

With that said, the discussion on this thread demonstrates that we can improve this utility to apply to a wider scope of problems, where strict idempotency guarantees are not required. Of the 2 possible solutions we have, I'm in favour of the initial suggestion to use a separate timeout counter for INPROGRESS records. It is simpler, requiring less work for users to implement. However, I haven't had time to work on this - and am not likely to have time for it in the near future. If anyone would like to submit a PR for it at a time when the repository is accepting feature requests, the team would be happy to review.

**Comment by cakepietoast** [comment]
Fundamentally, I'm still of the mind that deleting INPROGRESS records violates idempotency. When "stuck" INPROGRESS records occur, it is because there's no way for the utility to know whether the Lambda failed before, during, or after the unit of work its being asked to perform. As such, in the rare cases where this occurs, you would need to evaluate/investigate to be able to make the correct decision on how to proceed.

With that said, the discussion on this thread demonstrates that we can improve this utility to apply to a wider scope of problems, where strict idempotency guarantees are not required. Of the 2 possible solutions we have, I'm in favour of the initial suggestion to use a separate timeout counter for INPROGRESS records. It is simpler, requiring less work for users to implement, and less likely to cause issues similar to the one @n2N8Z mentions in the last comment.

I haven't had time to work on this - and am not likely to have time for it in the near future. If anyone would like to submit a PR for it at a time when the repository is accepting feature requests, the team would be happy to review.

**Comment by heitorlessa** [comment]
Sounds like we have a winner implementation then - use a timeout counter property and a OR as originally suggested by @n2N8Z.

Two clarifications tho:

- The timeout extension doesn't require any work from the customer, it'd happen transparently, no code change
- SIGTERM is guaranteed by Lambda Scheduler for internal/external extensions upon function timeout. SIGALRM, however, isn't and we wouldn't do that as a solution for accuracy and reliability reasons.

Given this is borderline bug, I'd be happy to review and contribute to any PR. If no one has the bandwidth, we can revisit in August-onwards timeframe.

Thanks a lot everyone

**Comment by michaelbrewer** [comment]
I am working on an initial draft PR based on what @n2N8Z has suggested #1198 Still untested and more to see the impact of the changes. 

This does not include fancy extension method @heitorlessa spoke about.

If i have time to complete the test coverage and do some end to end testing, then maybe @cakepietoast  or @heitorlessa  can look at it further.

Otherwise the docs will have to be updated with the list of caveats. :)

**Comment by michaelbrewer** [comment]
Deployed and tested a version of my PR #1198  and it works

template.yaml with powertools based on #1198 :

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Testing idempotency timeouts
Globals:
    Function:
        Timeout: 2

Resources:
  IdempotencyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -   AttributeName: id
            AttributeType: S
      KeySchema:
        -   AttributeName: id
            KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiration
        Enabled: true
      BillingMode: PAY_PER_REQUEST

  IdempotencyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: IdempotencyFunction
      CodeUri: src/
      Handler: app.handler
      Runtime: python3.9
      MemorySize: 512
      Layers: 
        - !Ref PowertoolsLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IdempotencyTable
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: example
          DYNAMODB_TABLE: !Ref IdempotencyTable

  PowertoolsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyLambdaLayer
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.9
```

app.py handler with a sleep longer than the function timeout:

```python
import time
from os import environ
from uuid import uuid4

from aws_lambda_powertools.utilities.idempotency import (
    DynamoDBPersistenceLayer,
    IdempotencyConfig,
    idempotent,
)

DYNAMODB_TABLE = environ["DYNAMODB_TABLE"]
config = IdempotencyConfig(function_timeout_clean_up=True)
persistence_layer = DynamoDBPersistenceLayer(table_name=DYNAMODB_TABLE)


@idempotent(persistence_store=persistence_layer, config=config)
def handler(event, context):
    time.sleep(1)
    uuid_value: str = str(uuid4())
    return {"message": uuid_value}
```
