### ISSUE TITLE
Feature request: utility function to get multiple parameters by name instead of path

### ISSUE THREAD

**Issue by hooverdc** [awslabs/aws-lambda-powertools-python#1040]
**Is your feature request related to a problem? Please describe.**

I have several functions in a severless application with several SSM parameters under the same path. Each function only needs access to some parameters and most functions will share some parameters but not all. I don't want functions to have access to parameters they don't require. I also don't want to call `get_parameter` for each parameter in order to keep cold start times down. I would like to be able to specify the parameter names and return them in one batch.

**Describe the solution you'd like**

A `get_parameters_by_name` function that accepts a list of strings of parameter names and returns a dict similar to the `get_parameters` function, but with the full parameter path as the key (presumably you could call this with parameters on different paths).

https://docs.aws.amazon.com/cli/latest/reference/ssm/get-parameters.html#get-parameters

**Describe alternatives you've considered**

Writing my own wrapper function that calls `get_parameters` from `boto3`.

**Additional context**
N/A

**Comment by heitorlessa** [comment]
Hey @hooverdc, thanks for creating this feature request! I believe this is best handled by your own custom wrapper, or perhaps approaching this differently.
 
>  I don't want functions to have access to parameters they don't require. I also don't want to call get_parameter for each parameter in order to keep cold start times down. 

Without knowing the number of parameters you have, their size, and how you create them, have you considered creating an aggregate parameter with multiple values?

**Example**. This allows e2e/integ scenarios to make a single call and get everything they need, while still having separate parameters that can be useful for other purposes like deployment time.

```yaml
Resources:
    ResourcesMapParameter:
        Type: AWS::SSM::Parameter
        Properties:
            Name: !Sub "/${Stage}/service/trip_ingestion/test/config"
            Type: String
            Description: Service Map with common resources used for integ/e2e testing
            Value: !Sub |
                {
                    "MobileTripsBucket": "${MobileTripsBucket}",
                    "MobileTripsQueue": "${MobileTripsQueue}",
                    "TripIngestionFunction": "${TripIngestionFunction}",
                    "MobileTripsApiEndpoint": "https://${MobileTripsApi}.execute-api.${AWS::Region}.amazonaws.com/${MobileTripsApi.Stage}/trip",
                    "Stage": "${Stage}"
                }
```

Hope that helps!

Thanks
