### ISSUE TITLE
Gitpod support

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#1104]
### Use case

To ease contributions by providing a zero install process like gitpod.io. Also mentioned in #1076

### Solution/User Experience

Fork project and open in gitpod.io before making PR requests. This is already available for the typescript version

Just adding `.gitpod.yml` would be enough

```yaml
# This configuration file was automatically generated by Gitpod.
# Please adjust to your needs (see https://www.gitpod.io/docs/config-gitpod-file)
# and commit this file to your remote git repository to share the goodness with others.

tasks:
  - init: make dev
```

I have test this, and it already works:

<img width="1699" alt="Screen Shot 2022-04-09 at 1 35 35 PM" src="https://user-images.githubusercontent.com/5442469/162590816-51ad8b0a-1555-4e10-9acb-7e15077dd0f4.png">

### Alternative solutions

There is already support for CodeSpaces, but this is not open to all developers.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)
