### ISSUE TITLE
Bug: Issue templates drop downs render wrong

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#1105]
### Expected Behaviour

Drop downs should format currently for:

- rfcs (`.github/ISSUE_TEMPLATE/rfc.yml`)
- bug reports (`.github/ISSUE_TEMPLATE/bug_report.yml`)
- static typing (`.github/ISSUE_TEMPLATE/static_typing.yml`)

How it should look:

<img width="377" alt="Screen Shot 2022-04-10 at 5 14 14 PM" src="https://user-images.githubusercontent.com/5442469/162646115-7291049d-17e4-4e2e-ab86-e1d5510b3b43.png">

### Current Behaviour

Currently drop downs include "label"

<img width="438" alt="Screen Shot 2022-04-10 at 4 58 35 PM" src="https://user-images.githubusercontent.com/5442469/162645504-388e301c-e22c-4f6a-afc8-35551d3bd65f.png">

### Code snippet

Current code snippet

```yaml
- type: dropdown
    id: runtime
    attributes:
      label: AWS Lambda function runtime
      options:
        - label: "3.6"
        - label: "3.7"
        - label: "3.8"
        - label: "3.9"
```

### Possible Solution

`.github/ISSUE_TEMPLATE/bug_report.yml` should be

```yaml
name: Bug report
description: Report a reproducible bug to help us improve
title: "Bug: TITLE"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report. Please add as much information as possible to help us reproduce, and remove any potential sensitive data.
  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected Behaviour
      description: Please share details on the behaviour you expected
    validations:
      required: true
  - type: textarea
    id: current_behaviour
    attributes:
      label: Current Behaviour
      description: Please share details on the current issue
    validations:
      required: true
  - type: textarea
    id: code_snippet
    attributes:
      label: Code snippet
      description: Please share a code snippet to help us reproduce the issue
      render: python
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: If known, please suggest a potential resolution
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please share how we might be able to reproduce this issue
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: AWS Lambda Powertools for Python version
      placeholder: "latest, 1.25.6"
      value: latest
    validations:
      required: true
  - type: dropdown
    id: runtime
    attributes:
      label: AWS Lambda function runtime
      options:
        - 3.6
        - 3.7
        - 3.8
        - 3.9
    validations:
      required: true
  - type: dropdown
    id: packaging
    attributes:
      label: Packaging format used
      options:
        - Lambda Layers
        - Serverless Application Repository (SAR) App
        - PyPi
      multiple: true
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Debugging logs
      description: If available, please share [debugging logs](https://awslabs.github.io/aws-lambda-powertools-python/#debug-mode)
      render: python
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---

        **Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.
```

`.github/ISSUE_TEMPLATE/rfc.yml` should be

```yaml
name: Request for Comments (RFC)
description: Feature design and detailed proposals
title: "RFC: TITLE"
labels: ["RFC", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a RFC. Please add as many details as possible to help further enrich this design.
  - type: input
    id: relation
    attributes:
      label: Is this related to an existing feature request or issue?
      description: Please share a link, if applicable
  - type: dropdown
    id: area
    attributes:
      label: Which AWS Lambda Powertools utility does this relate to?
      options:
        - Tracer
        - Logger
        - Metrics
        - Event Handler - REST API
        - Event Handler - GraphQL API
        - Middleware factory
        - Parameters
        - Batch processing
        - Typing
        - Validation
        - Event Source Data Classes
        - Parser
        - Idempotency
        - Feature flags
        - JMESPath functions
        - Other
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please provide an overview in one or two paragraphs
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Use case
      description: Please share the use case and motivation behind this proposal
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Please explain the design in detail, so anyone familiar with the project could implement it
      placeholder: What the user experience looks like before and after this design?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Out of scope
      description: Please explain what should be considered out of scope in your proposal
    validations:
      required: true
  - type: textarea
    id: challenges
    attributes:
      label: Potential challenges
      description: Nothing is perfect. Please share what common challenges, edge cases, unresolved areas, and suggestions on how to mitigate them
    validations:
      required: true
  - type: textarea
    id: integrations
    attributes:
      label: Dependencies and Integrations
      description: If applicable, please share whether this feature has additional dependencies, and how it might integrate with other utilities available
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: Please describe what alternative solutions to this use case, if any
      render: markdown
    validations:
      required: false
  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Acknowledgment
      options:
        - label: This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
          required: true
        - label: Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)
          required: false
  - type: markdown
    attributes:
      value: |
        ---

        **Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

        Metadata information for admin purposes, please leave them empty.

        * RFC PR:
        * Approved by: ''
        * Reviewed by: ''
```

`.github/ISSUE_TEMPLATE/static_typing.yml` should be

```yaml
name: Static typing mismatch report
description: Report a static type mismatch caught by a static type checker
title: "Static typing: TITLE"
labels: ["static_typing", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a static typing report. Please add as much information as possible to help us reproduce.

        Our preferred static type checker is [Mypy](https://mypy.readthedocs.io/en/stable/) using the following [configuration](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/mypy.ini).
  - type: dropdown
    id: tool
    attributes:
      label: Static type checker used
      options:
        - mypy (project's standard)
        - pyright/pylance
        - pyre
        - pytype
    validations:
      required: true
  - type: dropdown
    id: runtime
    attributes:
      label: AWS Lambda function runtime
      options:
        - 3.6
        - 3.7
        - 3.8
        - 3.9
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: AWS Lambda Powertools for Python version
      placeholder: "latest, 1.25.6"
      value: latest
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Static type checker info
      description: Please share your static type checker's output, its configuration, and how you typically run it
    validations:
      required: true
  - type: textarea
    id: code_snippet
    attributes:
      label: Code snippet
      description: Please share a code snippet to help us reproduce the issue
      render: python
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: If known, please suggest a potential resolution
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---

        **Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.
```

### Steps to Reproduce

Create new issue and click on drop downs

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

N/A

### Packaging format used

N/A

### Debugging logs

N/A

### More resources

- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Comment by michaelbrewer** [comment]
@heitorlessa - i have PR #1106 which fixes the drop downs.

**Comment by sthulb** [comment]
@michaelbrewer consider it done! It was also resolved already in commit [8bd5723e](https://github.com/awslabs/aws-lambda-powertools-python/commit/8bd5723e0e755e9798593efc7a351191c8983278)

**Comment by michaelbrewer** [comment]
@sthulb which is the same as my PR?

**Comment by michaelbrewer** [comment]
@sthulb now static typing template is gone? your implementation was not test like my PR

**Comment by michaelbrewer** [comment]
```yaml
name: Static typing mismatch report
description: Report a static type mismatch caught by a static type checker
title: "Static typing: TITLE"
labels: ["static_typing", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a static typing report. Please add as much information as possible to help us reproduce.

        Our preferred static type checker is [Mypy](https://mypy.readthedocs.io/en/stable/) using the following [configuration](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/mypy.ini).
  - type: dropdown
    id: tool
    attributes:
      label: Static type checker used
      options:
        - mypy (project's standard)
        - pyright/pylance
        - pyre
        - pytype
    validations:
      required: true
  - type: dropdown
    id: runtime
    attributes:
      label: AWS Lambda function runtime
      options:
        - 3.6
        - 3.7
        - 3.8
        - 3.9
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: AWS Lambda Powertools for Python version
      placeholder: "latest, 1.25.6"
      value: latest
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Static type checker info
      description: Please share your static type checker's output, its configuration, and how you typically run it
    validations:
      required: true
  - type: textarea
    id: code_snippet
    attributes:
      label: Code snippet
      description: Please share a code snippet to help us reproduce the issue
      render: python
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: If known, please suggest a potential resolution
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---

        **Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.
```
