### ISSUE TITLE
Bug: Future proof the python build process

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#1111]
### Expected Behaviour

Build should pass when adding python 3.10 compatibility 

### Current Behaviour

Builds will start to back when adding python 3.10 due to use of number instead of string	

### Code snippet

```python
name: Code quality

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make dev
      - name: Formatting and Linting
        run: make lint
      - name: Static type checking
        run: make mypy
      - name: Test with pytest
        run: make test
      - name: Security baseline
        run: make security-baseline
      - name: Complexity baseline
        run: make complexity-baseline
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          file: ./coverage.xml
          # flags: unittests
          env_vars: OS,PYTHON
          name: aws-lambda-powertools-python-codecov
          # fail_ci_if_error: true  # failing more consistently making CI unreliable despite all tests above passing
          token: ${{ secrets.CODECOV_TOKEN }}
```

### Possible Solution

```yaml
name: Code quality

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make dev
      - name: Formatting and Linting
        run: make lint
      - name: Static type checking
        run: make mypy
      - name: Test with pytest
        run: make test
      - name: Security baseline
        run: make security-baseline
      - name: Complexity baseline
        run: make complexity-baseline
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          file: ./coverage.xml
          # flags: unittests
          env_vars: OS,PYTHON
          name: aws-lambda-powertools-python-codecov
          # fail_ci_if_error: true  # failing more consistently making CI unreliable despite all tests above passing
          token: ${{ secrets.CODECOV_TOKEN }}
```

### Steps to Reproduce

Adding 3.10 as a number will fail builds eg: https://github.com/michaelbrewer/aws-lambda-events/commit/560d91ccf8191e71fef9bc19abe756c493b0461e

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.6

### Packaging format used

Lambda Layers

### Debugging logs

```python
NA
```
