### ISSUE TITLE
Bug: Static typing issue form is missing

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#1112]
### Expected Behaviour

Static typing form should be on the issue list

### Current Behaviour

Static typing form is missing

<img width="1622" alt="Screen Shot 2022-04-12 at 11 20 59 AM" src="https://user-images.githubusercontent.com/5442469/163028215-07596adf-2b01-4853-816f-5ad9cf6c6cdd.png">

### Code snippet

```yaml
name: Static typing mismatch report
description: Report a static type mismatch caught by a static type checker
title: "Static typing: TITLE"
labels: ["static_typing", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a static typing report. Please add as much information as possible to help us reproduce.

        Our preferred static type checker is [Mypy](https://mypy.readthedocs.io/en/stable/) using the following [configuration](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/mypy.ini).
  - type: dropdown
    id: tool
    attributes:
      label: Static type checker used
      options:
        - mypy (project's standard)
        - pyright/pylance
        - pyre
        - pytype
    validations:
      required: true
  - type: dropdown
    id: runtime
    attributes:
      label: AWS Lambda function runtime
      options:
        - "3.6
        - "3.7
        - "3.8
        - "3.9
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: AWS Lambda Powertools for Python version
      placeholder: "latest, 1.25.6"
      value: latest
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Static type checker info
      description: Please share your static type checker's output, its configuration, and how you typically run it
    validations:
      required: true
  - type: textarea
    id: code_snippet
    attributes:
      label: Code snippet
      description: Please share a code snippet to help us reproduce the issue
      render: python
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: If known, please suggest a potential resolution
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---

        **Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.
```

### Possible Solution

```yaml
name: Static typing mismatch report
description: Report a static type mismatch caught by a static type checker
title: "Static typing: TITLE"
labels: ["static_typing", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a static typing report. Please add as much information as possible to help us reproduce.

        Our preferred static type checker is [Mypy](https://mypy.readthedocs.io/en/stable/) using the following [configuration](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/mypy.ini).
  - type: dropdown
    id: tool
    attributes:
      label: Static type checker used
      options:
        - mypy (project's standard)
        - pyright/pylance
        - pyre
        - pytype
    validations:
      required: true
  - type: dropdown
    id: runtime
    attributes:
      label: AWS Lambda function runtime
      options:
        - 3.6
        - 3.7
        - 3.8
        - 3.9
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: AWS Lambda Powertools for Python version
      placeholder: "latest, 1.25.6"
      value: latest
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Static type checker info
      description: Please share your static type checker's output, its configuration, and how you typically run it
    validations:
      required: true
  - type: textarea
    id: code_snippet
    attributes:
      label: Code snippet
      description: Please share a code snippet to help us reproduce the issue
      render: python
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: If known, please suggest a potential resolution
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---

        **Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.
```

Or look at original PR https://github.com/awslabs/aws-lambda-powertools-python/pull/1106

### Steps to Reproduce

Create new issue from: https://github.com/awslabs/aws-lambda-powertools-python/issues/new/choose

Caused by commit : https://github.com/awslabs/aws-lambda-powertools-python/commit/8bd5723e0e755e9798593efc7a351191c8983278

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.6

### Packaging format used

Serverless Application Repository (SAR) App

### Debugging logs

```python
NA
```
