### ISSUE TITLE
Bug: Performance penalty when using SQS Batch Processor and code is bugged

### ISSUE THREAD

**Issue by j2clerck** [awslabs/aws-lambda-powertools-python#1149]
### Expected Behaviour

Lambda function fails fast due to code error.

### Current Behaviour

Lambda took 4s to fail.

### Code snippet

```python
import boto3
import os
import json
from aws_lambda_powertools import Logger
from aws_lambda_powertools.utilities.batch import (
    BatchProcessor,
    EventType,
    batch_processor,
)
from aws_lambda_powertools.utilities.data_classes.sqs_event import SQSRecord
from aws_lambda_powertools.utilities.typing import LambdaContext
from datetime import date

logger = Logger()
os.environ['unknown']
TARGET_BUCKET = os.environ["TARGET_BUCKET"]

session = boto3.Session()

processor = BatchProcessor(event_type=EventType.SQS)

today = date.today()

def record_handler(record: SQSRecord):
    return

@batch_processor(record_handler=record_handler, processor=processor)
def lambda_handler(event, context: LambdaContext):
    return processor.response()
```

### Steps to Reproduce

Deploy a Lambda function attached to SQS and put some error code outside of the handler.
My pattern is
S3 -> EventBridge -> SQS -> Lambda

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

Lambda Layers

### Debugging logs

```python
START RequestId: 98d2fe38-8621-5a90-983b-a4e47587d88c Version: $LATEST
[ERROR] KeyError: 'unknown'
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/index.py", line 15, in <module>
    os.environ['unknown']
  File "/var/lang/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
END RequestId: 98d2fe38-8621-5a90-983b-a4e47587d88c
REPORT RequestId: 98d2fe38-8621-5a90-983b-a4e47587d88c	Duration: 4126.55 ms	Billed Duration: 4127 ms	Memory Size: 256 MB	Max Memory Used: 22 MB	
XRAY TraceId: 1-6262f177-06bd6ddb3152f65a06a5012c	SegmentId: 696c0e692295678e	Sampled: true	
Unknown application error occurred
```

**Comment by heitorlessa** [comment]
Hey @j2clerck thanks for raising the issue as discussed. I suspect this is not us as it's failing at the Lambda worker level when importing your code package as a module (`bootstrap._gcd_import`), before it attempts to call your handler with the event where Powertools logic would kick in.

We'll look into it to confirm whether this happens regardless of Powertools. 


```python
return _bootstrap._gcd_import(name[level:], package, level)
```

**Comment by heitorlessa** [comment]
This is definitely interesting as I can reproduce but can't pinpoint to any logic that would cause it. Profiling doesn't show me anything obvious (I did find something else in Data Classes, but that's not it)

I'm gonna try profile in Prod, then try tweaking SQS poller settings like MaxRetry to 1 to rule out some hypothesis I have

![image](https://user-images.githubusercontent.com/3340292/165768496-83a5a08b-690d-44e9-846c-3a07ca2e0b08.png)

**Comment by heitorlessa** [comment]
Turns out it looks like an issue in the Lambda worker itself - The max duration matches with the timeout set in the Lambda. I also tried tweaking SQS maxReceive thinking it was related to SQS Poller retrying aggressively then calculating the duration but nope. Even removing Powertools I can get to the same effect. Changing my function timeout to 1s I get 1s duration, until I go above 4s, then it's always around 4s.

This is best resolved within Support or with the Lambda team directly

---

**2s timeout**
`2022/04/28/[$LATEST]1c5d96c399d343c6a8a82895aa9f3c7b 2022-04-28T14:14:02.844000 REPORT RequestId: 82c9123f-4377-5f4a-a76d-48dbe0122daf     Duration: 2027.33 ms    Billed Duration: 2000 ms        Memory Size: 256 MB     Max Memory Used: 18 MB`

**1s timeout**
`2022/04/28/[$LATEST]0fa5b3c000aa489f90abc7bf2ebe0ac3 2022-04-28T14:12:04.810000 REPORT RequestId: 2d7a6d73-3fe1-59ee-8be0-37979d003228       Duration: 1008.26 ms    Billed Duration: 1000 ms        Memory Size: 256 MB Max Memory Used: 14 MB`

`template.yaml`

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pt-issue-1149

  Sample SAM Template for pt-issue-1149

Globals:
  Function:
    Timeout: 2
    MemorySize: 256
    Runtime: python3.9
    Tracing: Active
    Environment:
        Variables:
            LOG_LEVEL: INFO
            POWERTOOLS_SERVICE_NAME: hello

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Layers:
        - arn:aws:lambda:eu-west-1:017000801446:layer:AWSLambdaPowertoolsPython:18
      Architectures:
        - x86_64
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt SampleQueue.QueueName
      Events:
          Batch:
              Type: SQS
              Properties:
                  Queue: !GetAtt SampleQueue.Arn
                  FunctionResponseTypes:
                      - ReportBatchItemFailures

  SampleDLQ:
      Type: AWS::SQS::Queue

  SampleQueue:
      Type: AWS::SQS::Queue
      Properties:
          VisibilityTimeout: 30 # Fn timeout * 6
          RedrivePolicy:
              maxReceiveCount: 1
              deadLetterTargetArn: !GetAtt SampleDLQ.Arn

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

```
