### ISSUE TITLE
Bug: TITLE

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#1213]
### Expected Behaviour

[AWS Serverless Application Model (SAM)](https://awslabs.github.io/aws-lambda-powertools-python/latest/core/metrics/#getting-started) template.yaml should be valid without errors

### Current Behaviour

Current example has missing attributes and generates the following errors.

<img width="941" alt="Screen Shot 2022-05-17 at 6 23 19 PM" src="https://user-images.githubusercontent.com/5442469/168937997-7aca0613-5db7-49eb-ad70-7722920116e0.png">

### Code snippet

```python
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: payment
        POWERTOOLS_METRICS_NAMESPACE: ServerlessAirline
```

### Possible Solution

Template yaml should be, like in PR #1122 , deployed example is here https://gyft.github.io/aws-lambda-powertools-python/latest/core/metrics/#getting-started

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: payment
          POWERTOOLS_METRICS_NAMESPACE: ServerlessAirline
```

### Steps to Reproduce

1. Go to https://awslabs.github.io/aws-lambda-powertools-python/latest/core/metrics/#getting-started
2. Copy `template.yml` example
3. Run `sam validate` and `cfn-lint`

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

### Debugging logs

```python
N/A
```
