### ISSUE TITLE
CORS error when using Lambda Powertool API with API Gateway and Lambda Proxy Integration

### ISSUE THREAD

**Issue by tushar-sahay-np** [awslabs/aws-lambda-powertools-python#2254]
### Expected Behaviour

After adding the CORS configuration in the contructor as mentioned in the documentation, the API, which is deployed on AWS API Gateway and backed by Lambda (via Lambda proxy integration) and should be succesfully called from a browser, which is a different origin.

### Current Behaviour

The API Gateway gives a 500 Internal server error for a pre-flight (CORS) OPTIONS request.

### Code snippet

```python
cors_config = CORSConfig(allow_origin="*", allow_headers=["X-Caller-Id", "X-Signature", "X-Request-Id"])
app = APIGatewayRestResolver(debug=True, cors=cors_config)

api_version: str = "/v1alpha1"

app.include_router(sample.router, prefix=api_version)

@logger.inject_lambda_context(correlation_id_path=correlation_paths.API_GATEWAY_REST)
@tracer.capture_lambda_handler
def lambda_handler(event: dict, context: LambdaContext) -> dict:
    logger.info("event is " + str(event))
    return app.resolve(event, context)
```

### Possible Solution

**Solution 1 (recommeded):** In class api_gateway.py, we have a method called **_not_found**. This method is primarily for requests that don't have a mapping in the configuration, and/or CORS preflight request. 

If the API method of the request is 'OPTIONS', then we return a response as :

return ResponseBuilder(Response(status_code=204, content_type=None, headers=headers, body="")).

SInce the body returned in the response is empty (""), the API gateway fails with a 500 internal server error because empty-string is not a valid json. Instead of empty-string, if we pass empty-json ("{}"), then the API-Gateway succesfully gives a 204 HTTP response.  

The whole method should look like: 

    def _not_found(self, method: str) -> ResponseBuilder:
        """Called when no matching route was found and includes support for the cors preflight response"""
        headers: Dict[str, Union[str, List[str]]] = {}
        if self._cors:
            logger.debug("CORS is enabled, updating headers.")
            headers.update(self._cors.to_dict())

            if method == "OPTIONS":
                logger.debug("Pre-flight request detected. Returning CORS with null response")
                headers["Access-Control-Allow-Methods"] = ",".join(sorted(self._cors_methods))
                return ResponseBuilder(Response(status_code=204, content_type=None, headers=headers, **body="{}"**))

**Solution 2 (works, but not-recommeded)**: 

In order to pass back an empty-json, when can write a middleware, which runs **after** the function-invocation. 

Inside this, we can check if the response-body = "", then replace with {}. The code can look something like this. 

@lambda_handler_decorator
def middleware_after(handler, event, context) -> Callable:
    response = handler(event, context)
    if response.get("body") == "":
        response["body"] = "{}"
    return response
    
 For my use-case, I am using option-2 correctly and it is working, but a permanent fix should be Solution 1 in my view.

### Steps to Reproduce

1) Create an API-Gateway and an API which deploys to Lambda (with method ANY- proxy integration).
2) Add CORS config to the app construction as mentioned in the above code-snippet. 
3) Create a sample UI (we have a stoplight documentation UI), and call the API.
4) The request should fail as :

Acess to fetch at '[https://sample-ap-southeast-1.amazonaws.com/payments'] from origin 'https://nomupay.stoplight.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.7

### Packaging format used

Serverless Application Repository (SAR) App

**Comment by tushar-sahay-np** [comment]
Created a PR for the same : https://github.com/awslabs/aws-lambda-powertools-python/pull/2255

**Comment by leandrodamascena** [comment]
Hi @tushar-sahay-np, thank you for opening this issue! I attempted to replicate the error you mentioned but unfortunately, I wasn't able to replicate it. I appreciate your help in reviewing the steps I took to simulate the error. Please let me know if there's anything important I may have missed or overlooked.

1 - For infrastructure I used this template: 

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Hello world event handler API Gateway

Globals:
  Api:
    TracingEnabled: true
  Function:
    Timeout: 5
    Runtime: python3.9
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: INFO
        POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
        POWERTOOLS_LOGGER_LOG_EVENT: true
        POWERTOOLS_SERVICE_NAME: example

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: hello_world/
      Description: API handler function
      Events:
        AnyApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+} # Send requests on any path to the lambda function
            Method: ANY # Send requests using any http method to the lambda function
```

2 - For the code I used this snippet:

```python
import requests
from requests import Response

from aws_lambda_powertools import Logger
from aws_lambda_powertools.event_handler import APIGatewayRestResolver, CORSConfig
from aws_lambda_powertools.logging import correlation_paths
from aws_lambda_powertools.utilities.typing import LambdaContext

logger = Logger()
cors_config = CORSConfig(allow_origin="*", allow_headers=["x-test"], max_age=300)
app = APIGatewayRestResolver(cors=cors_config)


@app.get("/todos")
def get_todos():
    todos: Response = requests.get("https://jsonplaceholder.typicode.com/todos")
    todos.raise_for_status()

    # for brevity, we'll limit to the first 10 only
    return {"todos": todos.json()[:10]}


@app.get("/todos/<todo_id>")
def get_todo_by_id(todo_id: str):  # value come as str
    todos: Response = requests.get(f"https://jsonplaceholder.typicode.com/todos/{todo_id}")
    todos.raise_for_status()

    return {"todos": todos.json()}


@app.get("/healthcheck", cors=False)  # optionally removes CORS for a given route
def am_i_alive():
    return {"am_i_alive": "yes"}


# You can continue to use other utilities just as before
@logger.inject_lambda_context(correlation_id_path=correlation_paths.API_GATEWAY_REST)
def lambda_handler(event: dict, context: LambdaContext) -> dict:
    return app.resolve(event, context)
```

3 - And to simulate a cross-domain call, I used this HTML served by a local Nginx

```html
<!DOCTYPE html>
<html>
<head>
  <title>AJAX GET Example</title>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function() {
      $('#loadDataButton').click(function() {
        $.ajax({
          url: 'https://xxxx.amazonaws.com/Prod/route-not-exists',  // URL of the server endpoint
          type: 'POST',                          // HTTP method
          contentType: 'application/json',
          dataType: 'json',                      // Expected data type
          crossDomain: true,
          data: JSON.stringify({ key: 'value' }),
          headers: { 'x-test': 'test' },
          success: function(data) {              // Success callback function
            // Process the retrieved data
            $('#result').text('Data loaded successfully: ' + JSON.stringify(data));
          },
          error: function(xhr, status, error) {  // Error callback function
            // Handle any error that occurred
            $('#result').text('Error: ' + error);
          }
        });
      });
    });
  </script>
</head>
<body>
  <h1>AJAX GET Example</h1>
  <button id="loadDataButton">Load Data</button>
  <div id="result"></div>
</body>
</html>
```

Without any changes to our current code, this worked exactly as expected. I have enabled requests/responses logging in API Gateway and we can see that it works as expected with `body=""`.

**HTTP calls**
![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/4295173/bb605ec0-93e8-4ae4-b71c-a1140e82cb6a)

**API Gateway logs**
![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/4295173/e5b747f3-bff4-481b-923f-c85e32391204)

Thank you.
