### ISSUE TITLE
Feature: Lambda Layers

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#25]
Leaving this for consideration and see if we have customer traction as we go GA - Not necessarily a blocker for GA but could be helpful to customers.

If you'd like this to be available for all Python runtimes supported in addition to PyPi, please leave a 👍

**Comment by djk** [comment]
Having an AWS managed & hosted lambda layer for this would be greatly appreciated!

**Comment by mwarkentin** [comment]
In the meantime, this is available in the super helpful https://github.com/keithrozario/Klayers repo.

**Comment by markusbecker** [comment]
@mwarkentin True that. Unfortunately not usable in an enterprise context since this source is not safe to work with. An official layer from AWS would really help without the heavy lifting from customers site.

**Comment by heitorlessa** [comment]
@am29d is currently working on it :) We're currently working on automating the Lambda Layers publishing pipeline to match our release process.

**Comment by markusbecker** [comment]
Awesome!

**Comment by keithrozario** [comment]
Can't wait!! :)

**Comment by heitorlessa** [comment]
hey everyone - **This is now AVAILABLE on SAR as of 1.4.0**: https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v1.4.0

We've also taken the time to update the release process to ensure both PyPi and SAR semantic versioning match, so you can trust the CHANGELOG as you would normally :)

Docs: https://awslabs.github.io/aws-lambda-powertools-python/#lambda-layer


cc @keithrozario @markusbecker  @mwarkentin @djk

**Comment by mwarkentin** [comment]
Is anyone aware of similar functionality for Serverless Framework that would allow us to embed the SAR app like this?

**Comment by am29d** [comment]
Hi @mwarkentin , the Serverless Framework can handle the `Transform` directive since v1.4.1:

https://github.com/serverless/serverless/pull/5997

This should like this:

```yaml
resources:
  Transform: AWS::Serverless-2016-10-31
  Resources:
    AwsLambdaPowertoolsPythonLayer:
      Type: AWS::Serverless::Application
      Properties:
        Location:
          ApplicationId: arn:aws:serverlessrepo:eu-west-1:057560766410:applications/aws-lambda-powertools-python-layer
          SemanticVersion: 1.3.1 # change to latest semantic version available in SAR
```
