### ISSUE TITLE
Maintenance: Refactor artifact name strategy for parallel uploads

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#3748]
### Why is this needed?

GitHub `actions/upload-artifact` v4 has a racing condition when uploading artifacts with the same artifact name in parallel.

For example, our Lambda Layer CDK artifacts are uploaded on a per region deploy in parallel using the [a static output name.](https://github.com/aws-powertools/powertools-lambda-python/blob/52dc1617f9b2d1454433ee4782e82525a647e6f5/.github/workflows/reusable_deploy_v2_layer_stack.yml#L202)

This caused [today's release](https://github.com/aws-powertools/powertools-lambda-python/actions/runs/7843824086) to fail partially - re-running failed jobs served as a workaround.

<img width="1655" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/3cff1e38-ea7b-4433-9078-c18493247760">

### Solution

Since it's a race condition on upload, we need a dynamic artifact name e.g., one per region. Then [merge these artifacts on download](https://github.com/aws-powertools/powertools-lambda-python/blob/52dc1617f9b2d1454433ee4782e82525a647e6f5/.github/workflows/publish_v2_layer.yml#L263).

> Updating to a dynamic name

```yaml
      - name: Save Layer ARN artifact
        if: ${{ inputs.stage == 'PROD' }}
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: cdk-layer-stack-{{ matrix.region }}
          path: ./layer/cdk-layer-stack/* # NOTE: upload-artifact does not inherit working-directory setting.
          if-no-files-found: error
          retention-days: 1
          overwrite: true   # still needed to allow failed retries
```

> Downloading all artifacts for all regions

```yaml
      - name: Download CDK layer artifact
        uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe # v4.1.2
        with:
          name: cdk-layer-stack
          path: cdk-layer-stack/
          merge-multiple: true
```

We'll need a testing environment to create a parallel job to test this out. 

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)
