### ISSUE TITLE
Bug: Lambda Function URL CORS issue - 

### ISSUE THREAD

**Issue by rbarman** [awslabs/aws-lambda-powertools-python#4163]
### Expected Behaviour

The expected behavior is to be able to successfully call a lambda function url.

### Current Behaviour

I get a CORs related error when I try to call the lambda function url in a basic web app.

test.html:1  Access to fetch at 'MY_URL/health' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'http://127.0.0.1:5500, http://127.0.0.1:5500', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Code snippet

template.yml

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Hello world event handler Lambda Function URL

Globals:
  Function:
    Timeout: 5
    Runtime: python3.11
    Tracing: Active
    Environment:
      Variables:
        POWERTOOLS_LOG_LEVEL: INFO
        POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
        POWERTOOLS_LOGGER_LOG_EVENT: true
        POWERTOOLS_SERVICE_NAME: example
    FunctionUrlConfig:
      Cors: # see CORS section
        AllowOrigins: ["*"]
        AllowHeaders: ["Content-Type", "Authorization", "X-Amz-Date"]
        MaxAge: 300

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: src
      Description: API handler function
      FunctionUrlConfig:
        AuthType: NONE # AWS_IAM for added security beyond sample documentation
```

app.py:

```
from aws_lambda_powertools import Logger, Tracer
from aws_lambda_powertools.event_handler import LambdaFunctionUrlResolver, CORSConfig
from aws_lambda_powertools.logging import correlation_paths
from aws_lambda_powertools.utilities.typing import LambdaContext

tracer = Tracer()
logger = Logger()
# cors_config = CORSConfig()
# app = LambdaFunctionUrlResolver(cors=cors_config)
app = LambdaFunctionUrlResolver()


@app.get("/health", cors=True)
@tracer.capture_method
def health():
    return {"status": "ok"}


# You can continue to use other utilities just as before
@logger.inject_lambda_context(correlation_id_path=correlation_paths.LAMBDA_FUNCTION_URL)
@tracer.capture_lambda_handler
def lambda_handler(event: dict, context: LambdaContext) -> dict:
    return app.resolve(event, context)
```

### Steps to Reproduce

* sam build
* sam deploy
* I try to call the health endpoint of the lambda function url in a very basic webpage:

```html
<html>
    <body>
        Testing API call...
    <script>
        fetch('MY_URL/health')
            .then(response => response.json())
            .then(data => {
                // Handle the response data here
                console.log(data);
            })
            .catch(error => {
                // Handle any errors that occur during the request
                console.error(error);
            });
    </script>
    </body>
</html>

```

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.11

### Packaging format used

Serverless Application Repository (SAR) App
