### ISSUE TITLE
Docs: Add llms.txt to documentation site

### ISSUE THREAD

**Issue by hjgraca** [awslabs/aws-lambda-powertools-python#6692]
### What were you searching in the docs?

Add support for llms.txt and llms-full.txt in Powertools for AWS documentation site
This will allow developers to add Powertools for AWS Lambda documentation context to their tools, IDEs, etc

### How can we improve?

Add support for llms.txt and llms-full.txt in Powertools for AWS documentation site

llms.txt will contain the links to the sections defined on the yaml
llms-full.txt will contain all the markdown text of those pages

### Got a suggestion in mind?

```yaml
plugins:
  - llmstxt:
      markdown_description: Powertools for AWS Lambda (Python) is a developer toolkit to implement Serverless best practices and increase developer velocity. It provides a suite of utilities for AWS Lambda Functions that makes tracing with AWS X-Ray, structured logging and creating custom metrics asynchronously easier.
      full_output: llms-full.txt
      sections:
        Project Overview:
          - index.md
          - changelog.md
          - upgrade.md
          - roadmap.md
        Core Utilities:
          - core/tracer.md
          - core/logger.md
          - core/metrics/index.md
          - core/metrics.md
          - core/metrics/datadog.md
          - core/event_handler/api_gateway.md
          - core/event_handler/appsync.md
          - core/event_handler/appsync_events.md
          - core/event_handler/bedrock_agents.md
        Utilities:
          - utilities/parameters.md
          - utilities/batch.md
          - utilities/typing.md
          - utilities/validation.md
          - utilities/data_classes.md
          - utilities/parser.md
          - utilities/idempotency.md
          - utilities/data_masking.md
          - utilities/feature_flags.md
          - utilities/streaming.md
          - utilities/middleware_factory.md
          - utilities/jmespath_functions.md
        Tutorial:
          - tutorial/index.md
        Processes:
          - security.md
          - automation.md
          - versioning.md
          - maintainers.md
        Contributing:
          - contributing/setup.md
          - contributing/getting_started.md
          - contributing/conventions.md
```

### Acknowledgment

- [x] I understand the final update might be different from my proposed suggestion, or refused.
