### ISSUE TITLE
What is the proper decoration for a {proxy+}

### ISSUE THREAD

**Issue by gwlester** [awslabs/aws-lambda-powertools-python#700]
**What were you trying to accomplish?**
We want to have a function handle proxying to an ELB. 

```yaml
  MicroServices:
    Type: AWS::Serverless::Function
    Properties:
      Handler: 'microServices.api_call_dispatcher'
      FunctionName: !Sub "micro-services"
      CodeUri: ../../src/microServices/
      Description: Implements calls to all of the micro servcies
      Runtime: python3.8
      Timeout: 60
      Layers:
        - !GetAtt rAwsLambdaPowertoolsPythonLayer.Outputs.LayerVersionArn
      Events:
        OnPremiseApiEvent:
          Type: Api
          Properties:
            Path: /proxy/{proxy+}
            Method: Any
            RestApiId:
              Ref: rApiGateway
```

```python
from aws_lambda_powertools.event_handler.api_gateway import ApiGatewayResolver

app = ApiGatewayResolver()

@app.get("/proxy/<proxy>")
def proxy(proxy):
    try:
        return on_premise_api_handler(app, proxy)  #

def lambda_handler(event, context):
    return app.resolve(event, context)
```

## Expected Behavior

Documentation containing the correct decoration for a proxy handler.

## Current Behavior

No documentation containing the correct decoration for a proxy handler.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Environment

* **Powertools version used**: 1.20.2
* **Packaging format (Layers, PyPi)**: Layer
* **AWS Lambda function runtime:** 3.8
* **Debugging logs**

> [How to enable debug mode](https://awslabs.github.io/aws-lambda-powertools-python/#debug-mode)**

```python
# paste logs here
```
