### ISSUE TITLE
sam local start-api + HTTP APIGW + event handler fails due to an unhandled exception

### ISSUE THREAD

**Issue by owen** [awslabs/aws-lambda-powertools-python#753]
**What were you trying to accomplish?**

I am building a SAM web application (Lambda + HTTP API Gateway) using these powertools and would like to test locally using `sam local start-api`

However, the local test fails – we crash because the SAM local APIGW container does not set a stage, and the event handler does not expect the stage to be `None`.

## Steps to Reproduce

1. `mkdir simplified-testcase`
2. Add the following files:

*template.yaml*
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

AwsLambdaPowertoolsPythonLayer:
  Type: AWS::Serverless::Application
  Properties:
    Location:
      ApplicationId: arn:aws:serverlessrepo:eu-west-1:057560766410:applications/aws-lambda-powertools-python-layer
      SemanticVersion: 1.21.0
Resources:
  HelloHandroll:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_handroll/
      Handler: hello.lambda_handler
      Runtime: python3.9
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /hellohand
            Method: get   
  HelloPowertools:
    Type: AWS::Serverless::Function
    Layers:
      - !GetAtt AwsLambdaPowertoolsPythonLayer.Outputs.LayerVersionArn
    Properties:
      CodeUri: hello_powertools/
      Handler: hello.lambda_handler
      Runtime: python3.9
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /hellopt
            Method: get
```

*hello_handroll/hello.py*

```python
def lambda_handler(event, context):
    return "world"
```

*hello_powertools/hello.py*

```python
from aws_lambda_powertools.event_handler.api_gateway import ApiGatewayResolver, ProxyEventType
from aws_lambda_powertools.logging.logger import set_package_logger

set_package_logger()
app = ApiGatewayResolver(proxy_type=ProxyEventType.APIGatewayProxyEventV2)

@app.get("/hello")
def get_hello():
    return "world"

def lambda_handler(event, context):
    return app.resolve(event, context)
```
3. `touch hello_powertools/__init__.py hello_handroll/__init__.py`
4. `poetry init` for a basic `pyproject.toml`
5. `poetry add aws-lambda-powertools`
6. `poetry export -o hello_powertools/requirements.txt`
7. `sam build`
8. `sam local start-api`
9. `curl localhost:3000/hellohand` -> returns `world` as expected
10. `curl localhost:3000/hellopt` -> returns:

```json
{
  "errorMessage": "can only concatenate str (not \"NoneType\") to str",
  "errorType": "TypeError",
  "requestId": "c59757cb-8289-42be-ac9e-904ea0a54c0e",
  "stackTrace": [
    "  File \"/var/task/hello.py\", line 12, in lambda_handler\n    return app.resolve(event, context)\n",
    "  File \"/var/task/aws_lambda_powertools/event_handler/api_gateway.py\", line 479, in resolve\n    return self._resolve().build(self.current_event, self._cors)\n",
    "  File \"/var/task/aws_lambda_powertools/event_handler/api_gateway.py\", line 531, in _resolve\n    path = self._remove_prefix(self.current_event.path)\n",
    "  File \"/var/task/aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py\", line 230, in path\n    return self.raw_path[len(\"/\" + stage) :]\n"
  ]
}
```

## Possible solution

I added a `print(event)` statement to capture the full request passed to the Lambda from SAM's local container (full log attached below).  I noted that `requestContext.stage` was `None`, which causes the exception here:

https://github.com/awslabs/aws-lambda-powertools-python/blob/989a4f63f0625d72cb9c203eb4255b951aed3099/aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py#L228-L231

What I *don't know* is, put simply, "whose problem this is".  AWS' documentation (https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) doesn't clearly show if that field can be null/None, so

* if `None` is allowed, this bug is valid
* if a stage must be provided, we can close this bug and I'll take the ticket over to aws/aws-sam-cli to see if their local APIGW image needs changing

I'll note that `sam validate` passed, and when deployed to AWS everything worked properly – this is strictly an issue with local development.

## Environment

* **Powertools version used**: 1.21.0
* **Packaging format (Layers, PyPi)**: Layers
* **AWS Lambda function runtime:** `python3.9`
* **Debugging logs**

```python
# Request generated by SAM's local API
{'version': '2.0', 'routeKey': 'GET /hellopt', 'rawPath': '/hellopt', 'rawQueryString': '', 'cookies': [], 'headers': {'Host': 'localhost:3000', 'User-Agent': 'curl/7.64.1', 'Accept': '*/*', 'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '3000'}, 'queryStringParameters': {}, 'requestContext': {'accountId': '123456789012', 'apiId': '1234567890', 'http': {'method': 'GET', 'path': '/hellopt', 'protocol': 'HTTP/1.1', 'sourceIp': '127.0.0.1', 'userAgent': 'Custom User Agent String'}, 'requestId': 'f4f3f188-adde-4c21-bcc5-6d76072e61fa', 'routeKey': 'GET /hellopt', 'stage': None}, 'body': '', 'pathParameters': {}, 'stageVariables': None, 'isBase64Encoded': False}
```

```
# Logs from sam local start-api, with debugging:

Mounting HelloHandroll at http://127.0.0.1:3000/hellohand [GET]
Mounting HelloPowertools at http://127.0.0.1:3000/hellopt [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2021-10-06 17:12:11  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
Invoking hello.lambda_handler (python3.9)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-python3.9:rapid-1.33.0-x86_64.

Mounting /private/tmp/simplified-testcase/.aws-sam/build/HelloPowertools as /var/task:ro,delegated inside runtime container
START RequestId: c59757cb-8289-42be-ac9e-904ea0a54c0e Version: $LATEST
2021-10-06 21:12:24,043 aws_lambda_powertools.event_handler.api_gateway [DEBUG] Adding route using rule /hello and method GET
2021-10-06 21:12:24,044 aws_lambda_powertools.event_handler.api_gateway [DEBUG] Converting event to API Gateway HTTP API contract
    return self.raw_path[len("/" + stage) :]ities/data_classes/api_gateway_proxy_event.py", line 230, in path
END RequestId: c59757cb-8289-42be-ac9e-904ea0a54c0e
REPORT RequestId: c59757cb-8289-42be-ac9e-904ea0a54c0e	Init Duration: 0.32 ms	Duration: 1347.47 ms	Billed Duration: 1348 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
No Content-Type given. Defaulting to 'application/json'.

```
